# Generated by Django 4.1.7 on 2023-06-14 14:55

from django.db import migrations, models
import points.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_class', models.CharField(max_length=10, verbose_name='Номер кабинета \n Пример : РИ 120')),
                ('id_of_point', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Номер аудитории',
                'verbose_name_plural': 'Аудитории',
                'db_table': 'Classrooms',
            },
        ),
        migrations.CreateModel(
            name='Institue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ST', 'Улица'), ('RI', 'РИ'), ('T', 'Т'), ('GK', 'ГУК')], max_length=2, verbose_name='Название')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Интститут',
                'verbose_name_plural': 'Интституты',
                'db_table': 'Institues',
            },
        ),
        migrations.CreateModel(
            name='MapImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institue', models.CharField(choices=[('ST', 'Улица'), ('RI', 'РИ'), ('T', 'Т'), ('GK', 'ГУК')], default='ST', max_length=2, verbose_name='Институт')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('image', models.ImageField(upload_to='static/images/maps/', verbose_name='Файл')),
                ('is_have_points', models.BooleanField(default=False, verbose_name='Наличие точек в бд')),
            ],
            options={
                'db_table': 'Images_Map',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point_id', models.IntegerField()),
                ('end_point_id', models.IntegerField()),
                ('path', models.JSONField(default=points.models.Path.get_default_pathes)),
            ],
            options={
                'verbose_name': 'Начальная точка | Конечная точка',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'Pathes',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institue', models.CharField(choices=[('ST', 'Улица'), ('RI', 'РИ'), ('T', 'Т'), ('GK', 'ГУК')], default='ST', max_length=2)),
                ('type', models.IntegerField(choices=[(0, 'улица'), (1, 'коридор'), (2, 'перед аудиторией'), (3, 'аудитория'), (4, 'лестница'), (5, 'входная дверь')], default=1)),
                ('relativeX', models.IntegerField()),
                ('relativeY', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('conns', models.JSONField(default=points.models.Point.get_default_connections)),
            ],
            options={
                'verbose_name': 'Институт | Этаж | X | Y или Номер кабинета',
                'verbose_name_plural': 'Точки',
                'db_table': 'Points',
            },
        ),
    ]
