# Generated by Django 4.1.7 on 2023-05-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/maps/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='path',
            options={'verbose_name': 'Начальная точка | Конечная точка', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number_of_class',
            field=models.CharField(max_length=10, verbose_name='Номер кабинета \n Пример : РИ 120'),
        ),
    ]
