# Generated by Django 4.1.7 on 2023-04-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point_id', models.IntegerField()),
                ('end_point_id', models.IntegerField()),
                ('path', models.JSONField(default={'connections': []})),
            ],
            options={
                'verbose_name': 'Начальная точка ID | Конечная точка ID',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': 'Тип точки | Этаж | X | y', 'verbose_name_plural': 'Точки'},
        ),
        migrations.AlterField(
            model_name='points',
            name='connections',
            field=models.JSONField(default={'connections': []}),
        ),
        migrations.AlterField(
            model_name='points',
            name='type',
            field=models.CharField(choices=[('0', 'улица'), ('1', 'коридор'), ('2', 'пре аудитория'), ('3', 'аудитория'), ('4', 'лестница'), ('5', 'входная дверь')], default='1', max_length=1),
        ),
    ]
