# Generated by Django 4.1.7 on 2023-05-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_mapimages_alter_path_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapimages',
            name='floor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapimages',
            name='institue',
            field=models.CharField(choices=[('ST', 'Улица'), ('RI', 'РИ'), ('T', 'Т')], default='ST', max_length=2),
        ),
    ]
